# Part -I (Broadcasting, Reshaping, Sorting and Iterating NumPy Arrays)

## Learning agenda 
1. Broadcasting NumPy Arrays
2. Reshaping NumPy Arrays
    - Use `shape` attribute (in-place operation)
    - Use `np.reshape()` method (shallow copy)
    - Use `np.resize()` method (deep copy)
    - Use `ndarray.transpose()` method (shallow copy)
    - Use `np.swapaxes()`method (shallow copy)
    - Use `np.flatten()` method (deep copy)
3. Sorting Arrays using `np.sort()` Method
4. Iterating NumPy Arrays

## 1. Broadcasting numPy Arrays
- Numpy arrays also support **broadcasting**, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. 
- Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
- Two dimensions are compatible when
    - they are equal, or
    - one of them is 1

>**Review of Arithmetic operations with numPy arrays of same shape:**

In [1]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,50, size=5)
arr2 = np.random.randint(1,10, size=5)
print("arr1: ", arr1)
print("arr2: ", arr2)

# After the operation a new `ndarray` is returned
print("arr1 + arr2 = ",      arr1 + arr2)    
print("arr1 / arr2 = ", arr1 / arr2)    
print("arr1 // arr2 = ",   arr1  // arr2)  
print("arr1 ** arr2 = ",      arr1  ** arr2)   

arr1:  [47 47  9  8 43]
arr2:  [1 6 6 4 6]
arr1 + arr2 =  [48 53 15 12 49]
arr1 / arr2 =  [47.          7.83333333  1.5         2.          7.16666667]
arr1 // arr2 =  [47  7  1  2  7]
arr1 ** arr2 =  [         47 -2105686559      531441        4096  2026395753]


### a. Arithmetic of 1-Dimensional Array with a Scalar Value

In [2]:
# Consider adding a scalar value 'a' to a 1-D numPy array
arr1 = np.array([1, 2, 3, 4])
print("arr1: ", arr1)
print("arr1.shape: ", arr1.shape)
a = 2
print("a: ", a)

arr1:  [1 2 3 4]
arr1.shape:  (4,)
a:  2


In [3]:
# The scalar value is replicated to match the shape of arr1 before the operation
#   [2  2  2  2] 

arr2 = arr1 + a 
print("arr2: \n", arr2)

arr2: 
 [3 4 5 6]


### b. Arithmetic of 2-Dimensional Array with a Scalar Value

In [4]:
# Consider adding a scalar value 'a' to a 2-D numPy array
arr1 = np.array([[1, 2, 3], [1, 2, 3]])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)
a = 2
print("a: ", a)

arr1:
 [[1 2 3]
 [1 2 3]]
arr1.shape:  (2, 3)
a:  2


In [5]:
# The scalar value is replicated to match the shape of arr1 before the operation
#   2  2  2 
#   2  2  2 

arr2 = arr1 + a 
print("arr2: \n", arr2)

arr2: 
 [[3 4 5]
 [3 4 5]]


### c. Arithmetic of 1-Dimensional Array with a 2-Dimensional Array

**Example 1:** Consider adding a 2-D array (3x4) to a 1-D array with 4 values

In [6]:
arr1 = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [2, 7, 8, 9]])
arr2 = np.array([4, 2, 3, 2])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[1 2 3 4]
 [3 4 5 6]
 [2 7 8 9]]
arr1.shape:  (3, 4)
arr2:
 [4 2 3 2]
arr2.shape:  (4,)


In [7]:
# The only row of arr2 is replicated twice before the operation
#   4  2  3  5
#   4  2  3  5
#   4  2  3  5

arr3 = arr1 + arr2 

print("arr3: \n", arr3)

arr3: 
 [[ 5  4  6  6]
 [ 7  6  8  8]
 [ 6  9 11 11]]


**Example 2:** Consider adding a 2-D array (4x2) to a 1-D array with 2 values

In [8]:
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)

arr2 = np.array([4, 5])
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
arr1.shape:  (4, 2)
arr2:
 [4 5]
arr2.shape:  (2,)


In [9]:
# The only row of arr2 is replicated three times before the operation
#   4  5
#   4  5
#   4  5
#   4  5
arr3 = arr2 + arr1 

print("arr3: \n", arr3)

arr3: 
 [[ 5  7]
 [ 7  9]
 [ 9 11]
 [11 13]]


### d. Arithmetic of two 2-Dimensional Arrays

**Example 1:** Consider adding elements of a 2-D array (2x3) with another 2-D array (3x1)

In [10]:
arr1 = np.array([[5, 3, 2],[3, 4, 5], [7, 1, 4]])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)

arr2 = np.array([[100], [200], [300]])
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[5 3 2]
 [3 4 5]
 [7 1 4]]
arr1.shape:  (3, 3)
arr2:
 [[100]
 [200]
 [300]]
arr2.shape:  (3, 1)


In [11]:
# The only column of arr2 is replicated twice before the operation
#   100   100   100
#   200   200   300
#   300   300   300

arr3 = arr1 + arr2 

print("arr3: \n", arr3)

arr3: 
 [[105 103 102]
 [203 204 205]
 [307 301 304]]


**Points to Ponder in Arithmetic and Broadcasting:**
>- Arithmetic between elements of two numPy arrays works fine if both the arrays are of same shape.
>- Arithmetic between a numPy array and a scalar value works fine due to broadcasting.
>- Arithmetic between elements of two numPy arrays with different dimensions will work, if and only if the array with smaller dimension can be replicated to match the shape of other array (as in above examples)

**Example 1: Broadcast Error**

In [12]:
# Consider adding a 2-D array (2x3) to a 1-D array with 2 values
arr1 = np.array([[1, 2, 3], [1, 2, 3]])
arr2 = np.array([1,2])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[1 2 3]
 [1 2 3]]
arr1.shape:  (2, 3)
arr2:
 [1 2]
arr2.shape:  (2,)


In [13]:
# Since arr2 cannot be replicated to match the shape of arr1,
# (last dimension of `arr1` i.e., 3 does not match with the first dimension of `arr2` i.e., 2)
# therefore, broadcasting is unsuccessful and will flag an error
arr3 = arr1 + arr2 

print("arr3: \n", arr3)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**Example 2: Broadcast Error**

In [14]:
# Consider adding a 2-D array (2x3) to a 1-D array with 2 values
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)


arr2 = np.array([[4], [5], [6], [5]])
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
arr1.shape:  (4, 2)
arr2:
 [[4]
 [5]
 [6]
 [5]]
arr2.shape:  (4, 1)


In [15]:
# Since arr2 cannot be replicated to match the shape of arr1,
# (last dimension of `arr1` i.e., 2 does not match with the first dimension of `arr2` i.e., 3)
# therefore, broadcasting is unsuccessful and will flag an error
try:
    arr3 = arr1 + arr2 
    print("arr3: \n", arr3)
except ValueError as e:
    print(e)

arr3: 
 [[ 5  6]
 [ 8  9]
 [11 12]
 [12 13]]


**Example 3: Broadcast Error**

In [16]:
arr1 = np.array([[5, 3, 2],[3, 4, 5], [7, 1, 4]])
print("arr1:\n", arr1)
print("arr1.shape: ", arr1.shape)

arr2 = np.array([[100], [200]])
print("arr2:\n", arr2)
print("arr2.shape: ", arr2.shape)

arr1:
 [[5 3 2]
 [3 4 5]
 [7 1 4]]
arr1.shape:  (3, 3)
arr2:
 [[100]
 [200]]
arr2.shape:  (2, 1)


In [17]:
# Since arr2 cannot be replicated to match the shape of arr1,
# (last dimension of `arr1` i.e., 3 does not match with the first dimension of `arr2` i.e., 2)
# therefore, broadcasting is unsuccessful and will flag an error
try:
    arr3 = arr1 + arr2 
    print("arr3: \n", arr3)
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (2,1) 


## 2. Reshaping Arrays
- Reshaping numpy array simply means changing the shape of the given array, shape basically tells the number of elements and dimension of array.
- By reshaping an array we can add or remove dimensions or change number of elements in each dimension.
- There are different ways that reshape numPy arrays:
    - Changing the `shape` attribute (in-place operation)
    - Use `np.reshape()` method (shallow copy)
    - Use `np.resize()` method (deep copy)
    - Use `ndarray.transpose()` method (shallow copy)
    - Use `np.swapaxes()`method (shallow copy)
    - Use `ndarray.flatten()` method (deep copy)

### a. Change the `np.shape` Attribute
- Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same.
- No new array is created, rather the change of shape occurs in-place.

In [18]:
import numpy as np
arr1 = np.arange(24)
print("arr1:", arr1)
print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Strides:", arr1.strides)

arr1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Dimensions: 1
Shape: (24,)
Strides: (4,)


In [19]:
#Changing the shape attribute (array size must remain same)
arr1.shape = (6, 4)
print("arr1: \n", arr1)
print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Strides:", arr1.strides)

arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Dimensions: 2
Shape: (6, 4)
Strides: (16, 4)


In [20]:
#Changing the shape attribute (array size must remain same)
arr1.shape = (2, 4, 3)
print("arr1: \n", arr1)
print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Strides:", arr1.strides)

arr1: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
Dimensions: 3
Shape: (2, 4, 3)
Strides: (48, 12, 4)


### b. Use the `np.reshape()` Method

```
np.reshape(arr, newshape)
```

- The `np.reshape()` method takes the input array, then a tuple that defines the shape of the new array and returns a new array, which shares the same memory as the original array. You can think it as shallow copy in Python, where if you change the data in one array, the corresponding data in the other array is also modified.

**Example 1:** Reshaping from 1-D numPy Arrays to 2-D numPy Arrays

In [21]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: ", arr1, "\nShape: ", arr1.shape)

Original Array:  [1 2 3 4 5 6] 
Shape:  (6,)


In [22]:
# Changing the dimension of array using reshape()
arr2 = np.reshape(arr1, (2, 3))
print("Reshaped Array: \n", arr2, "\nShape: ", arr2.shape)

Reshaped Array: 
 [[1 2 3]
 [4 5 6]] 
Shape:  (2, 3)


In [23]:
# make change in one of the arrays, the change is reflected in both
arr2[0][0] = 99
print("Original Array: ", arr1)
print("Reshaped Array: \n", arr2)
print("id(arr1): ", id(arr1))
print("id(arr2): ",id(arr2))

Original Array:  [99  2  3  4  5  6]
Reshaped Array: 
 [[99  2  3]
 [ 4  5  6]]
id(arr1):  1862231192368
id(arr2):  1862218420880


**Example 2:** Reshaping from 1-D numPy Arrays to 3-D numPy Arrays

In [24]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original Array: ", arr1, "\nShape: ", arr1.shape)

arr2 = np.reshape(arr1, (2, 2, 3))
print("\nReshaped Array: \n", arr2, "\nShape: ", arr2.shape)

Original Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12] 
Shape:  (12,)

Reshaped Array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
Shape:  (2, 2, 3)


**Example 3:** Flattening Arrays. You can convert an array of an unknown dimension to a 1D array using `np.reshape(-1) `

In [25]:
arr1 = np.array([[1, 2, 3], [6, 7, 8], [4, 5, 6], [11, 14, 10]])
print("Original Array: \n", arr1, "\nShape: ", arr1.shape)

arr2 = np.reshape(arr1, (-1))
print("\nReshaped Array: \n", arr2, "\nShape: ", arr2.shape)

Original Array: 
 [[ 1  2  3]
 [ 6  7  8]
 [ 4  5  6]
 [11 14 10]] 
Shape:  (4, 3)

Reshaped Array: 
 [ 1  2  3  6  7  8  4  5  6 11 14 10] 
Shape:  (12,)


**Example 4:** Reshaping an array back to its original dimensions. If you applied the `np.reshape()` method to an array and you want to get the original shape of the array back, you can call the reshape method on that array again.

In [26]:
arr1 = np.array([[1, 2, 3], [6, 7, 8], [4, 5, 6], [11, 14, 10]])
print("Original Array: \n", arr1, "\nShape: ", arr1.shape)

arr2 = np.reshape(arr1, (2, 6))
print("\nReshaped Array: \n", arr2, "\nShape: ", arr2.shape)

# covert the array into original shape again
arr3 = np.reshape(arr2, (4,3))
print("\nReshaped to Original Shape: \n", arr3, "\nShape: ", arr3.shape)

Original Array: 
 [[ 1  2  3]
 [ 6  7  8]
 [ 4  5  6]
 [11 14 10]] 
Shape:  (4, 3)

Reshaped Array: 
 [[ 1  2  3  6  7  8]
 [ 4  5  6 11 14 10]] 
Shape:  (2, 6)

Reshaped to Original Shape: 
 [[ 1  2  3]
 [ 6  7  8]
 [ 4  5  6]
 [11 14 10]] 
Shape:  (4, 3)


**Example 5:** You can reshape to any shape, the only requirement is that the total elements in both the arrays should be same

In [27]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.reshape(arr1, (3, 2))
arr2

ValueError: cannot reshape array of size 9 into shape (3,2)

### c.  Use `np.resize()` Method
```
np.resize(arr, newshape)
```
- Like `np.reshape()` method, the `np.resize()` method also takes the input array and a tuple that defines the shape of the array, with one main difference and that is:
    - If the `newshape` argument mismatch with the size of `arr`, it do not raise error. The new array is formed from the data in the old array, repeated if necessary to fill out the required number of elements.  

**Example 1:** Resizing from 1-D numPy Arrays to 2-D numPy Arrays. The new array doesn’t share the same memory with the original array. The data change in one array is not mapped to the other.

In [28]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: ", arr1, "\nShape: ", arr1.shape)

Original Array:  [1 2 3 4 5 6] 
Shape:  (6,)


In [29]:
# Changing the dimension of array using reshape()
arr2 = np.resize(arr1, (2, 3))
print("Resized Array: \n", arr2, "\nShape: ", arr2.shape)

Resized Array: 
 [[1 2 3]
 [4 5 6]] 
Shape:  (2, 3)


In [30]:
# make change in one of the arrays, the change is NOT reflected in both
arr2[0][0] = 99
print("Original Array: ", arr1)
print("Resized Array: \n", arr2)
print("id(arr1): ", id(arr1))
print("id(arr2): ",id(arr2))

Original Array:  [1 2 3 4 5 6]
Resized Array: 
 [[99  2  3]
 [ 4  5  6]]
id(arr1):  1862237704464
id(arr2):  1862237707056


**Example 2:** The `np.resize()` method allows you to resize an array to a new array having larger size than the original array. In this scenario, it fills the remaining array with repeated copies of original array elements

In [31]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: ", arr1, "\nShape: ", arr1.shape)

Original Array:  [1 2 3 4 5 6] 
Shape:  (6,)


In [32]:
arr2 = np.resize(arr1, (4,4))
print("\nResized Array: \n", arr2, "\nShape: ", arr2.shape)


Resized Array: 
 [[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]
 [1 2 3 4]] 
Shape:  (4, 4)


**Example 3:** The `np.resize()` method allows you to resize an array to a new array having smaller size than the original array.

In [33]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original Array: ", arr1, "\nShape: ", arr1.shape)

Original Array:  [1 2 3 4 5 6 7 8] 
Shape:  (8,)


In [34]:
arr2 = np.resize(arr1, (3, 2))
print("\nResized Array: \n", arr2, "\nShape: ", arr2.shape)


Resized Array: 
 [[1 2]
 [3 4]
 [5 6]] 
Shape:  (3, 2)


### d. The `ndarray.transpose()` Method
```
ndarray.transpose()
```
- It has no impact on 1-D array
- For a 2-D array, this is a standard matrix transpose.
- For an n-D array, if axes are given, their order indicates how the axes are permuted
- Returns a view of the array with axes transposed, so this is an in-place operation.

In [35]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original Array: \n", arr1, "\nShape: ", arr1.shape)

#Reshape array using transpose method
arr2 = arr1.transpose()
print("\nTransposed array: \n", arr2,  "\nShape: ", arr2.shape)

## make change in one of the arrays, the change is reflected in both
arr2[1][1] = 99
print("\nOriginal Array: \n", arr1)
print("Transposed Array: \n", arr2)

Original Array: 
 [[1 2 3 4]
 [5 6 7 8]] 
Shape:  (2, 4)

Transposed array: 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]] 
Shape:  (4, 2)

Original Array: 
 [[ 1  2  3  4]
 [ 5 99  7  8]]
Transposed Array: 
 [[ 1  5]
 [ 2 99]
 [ 3  7]
 [ 4  8]]


### e. The `np.swapaxes()` Method
- The `np.swapaxes()` method is used to interchange two axes of an array.
```
np.swapaxes(arr, axis1, axis2)
```
    - `arr`: Input array whose axes are to be swapped
    - `axis1`: First axis
    - `axis2`: Second axis

- For NumPy >= 1.10.0, if `arr` is an ndarray, then a view of `arr` is returned.

**Example 1:** Swapping axes of a 2-D array

In [36]:
arr1 = np.arange(8).reshape(2,4) 
print("Original Array: \n", arr1, "\nShape: ", arr1.shape)

Original Array: 
 [[0 1 2 3]
 [4 5 6 7]] 
Shape:  (2, 4)


In [37]:
#Reshape array using swapaxes() method
arr2 = np.swapaxes(arr1,0, 1)
print("\nNew array: \n", arr2,  "\nShape: ", arr2.shape)


New array: 
 [[0 4]
 [1 5]
 [2 6]
 [3 7]] 
Shape:  (4, 2)


In [38]:
## make change in one of the arrays, the change is reflected in both
arr2[1][1] = 99
print("\nOriginal Array: \n", arr1)
print("\nNew Array: \n", arr2)


Original Array: 
 [[ 0  1  2  3]
 [ 4 99  6  7]]

New Array: 
 [[ 0  4]
 [ 1 99]
 [ 2  6]
 [ 3  7]]


**Example 2:** Swapping axes of a 3-D array

In [39]:
arr1 = np.arange(8).reshape(2,2,2) 
print("Original Array: \n", arr1, "\nShape: ", arr1.shape)

Original Array: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 
Shape:  (2, 2, 2)


In [40]:
#Reshape array using swapaxes() method
arr2 = np.swapaxes(arr1,1, 2)
print("\nNew array: \n", arr2,  "\nShape: ", arr2.shape)


New array: 
 [[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]] 
Shape:  (2, 2, 2)


### f. The `ndarray.flatten()` Method
- The `ndarry.flatten()` method is used to flatten a Multi-Dimensional array/matrix to one dimension. 
```
ndarray.flatten(order= 'C')
```
   - Default order is 'C’, means to flatten in row-major order. 
   - You can pass ‘F’ (FORTRAN) means to flatten in column-major.
- Returns a copy of the array, flattened to one dimension.

In [41]:
arr1 = np.arange(12).reshape(4,3) 
print("Original Array: \n", arr1, "\nDimensions: ", arr1.ndim)

Original Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
Dimensions:  2


In [42]:
# flatten the array in row-major order
arr2 = arr1.flatten(order = 'C')
print("\nFlattened array in row major order \n", arr2, "\nDimensions: ", arr2.ndim)

# flatten the array in column-major order
arr3 = arr1.flatten(order = 'F')
print("\nFlattened array in cloumn major order \n", arr3, "\nDimensions: ", arr3.ndim)


Flattened array in row major order 
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 
Dimensions:  1

Flattened array in cloumn major order 
 [ 0  3  6  9  1  4  7 10  2  5  8 11] 
Dimensions:  1


## 3. Sorting Arrays using `np.sort()` Method
- The `np.sort()` method returns a sorted copy of an array.
- If axis is not specified, values can be of any shape and will be flattened before use
```
np.sort(arr1, axis=-1, kind=None)
```
    - `arr` : Array to be sorted.
    - `axis` : Axis along which we need array to be started. The default is -1, which sorts along the last axis. 0 stands for sorting along first axis. If metioned None, the array is flattened before sorting.
    - `kind` : default is 'quicksort', others can be 'mergesort', 'heapsort'

### a. Sorting a 1-D Array

In [43]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 100, size = 5)
print("arr1 = ", arr1)

arr1 =  [50 51 31 92 97]


In [44]:
arr2 = np.sort(arr1)
print("arr2 = ", arr2)

arr2 =  [31 50 51 92 97]


### b. Sorting a 2-D Array

**Example 1:** Sorting a 2-D array with `axis=None`, array is flattened before sorting

In [45]:
arr1 = np.random.randint(low = 1, high = 100, size = (3,3))
print("arr1: \n", arr1)

arr1: 
 [[16 78 68]
 [43 21 38]
 [26 92 77]]


In [46]:
arr2 = np.sort(arr1, axis = None)        
print ("\nSorting along axis=None: \n", arr2)


Sorting along axis=None: 
 [16 21 26 38 43 68 77 78 92]


**Example 2:** Sorting a 2-D array with `axis=0`, vertical axis, top to bottom

In [47]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[7 2 8]
 [7 2 6]
 [6 5 3]]


In [48]:
arr2 = np.sort(arr1, axis = 0)        
print ("\nSorting along axis=0: \n", arr2)      


Sorting along axis=0: 
 [[6 2 3]
 [7 2 6]
 [7 5 8]]


**Example 3:** Sorting a 2-D array with `axis=1`, horizontal axis, left to right

In [49]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[5 3 8]
 [4 9 2]
 [8 4 7]]


In [50]:
arr2 = np.sort(arr1, axis = 1)        
print ("\nSorting along axis=1: \n", arr2) 


Sorting along axis=1: 
 [[3 5 8]
 [2 4 9]
 [4 7 8]]


## 4. Iterating numPy Arrays
- Iterating over `ndarrays` is very similar to iterating over regular python arrays. 
- Remember, iterating over multidimensional arrays is done with respect to the first axis.

**Example 1:** Iterating over 1-D numPy array

In [51]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
for value in arr1:
    print(value, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

**Example 2:** Iterating over 2-D numPy array is done w.r.t first axis, i.e., zero axis (column wise). In simple words in the first iteration you will get the first row, in second iteration you will get the 2nd row and so on...

In [53]:
arr1 = np.arange(12).reshape(4, 3)
print("arr1: \n",arr1)

arr1: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
for zero_axis in arr1:
    print("Iteration:")
    print(zero_axis)

Iteration:
[0 1 2]
Iteration:
[3 4 5]
Iteration:
[6 7 8]
Iteration:
[ 9 10 11]


**Example 3:** Iterating over 2-D numPy array

In [55]:
arr1 = np.arange(8).reshape(2, 4)
print("arr1: \n",arr1)

arr1: 
 [[0 1 2 3]
 [4 5 6 7]]


In [56]:
for zero_axis in arr1:
    print("Iteration:")
    print(zero_axis)

Iteration:
[0 1 2 3]
Iteration:
[4 5 6 7]


**Example 4:** Iterating over 3-D numPy array is done w.r.t first axis, i.e., zero axis (level wise). In simple words in the first iteration you will get the first row, in second iteration you will get the 2nd row and so on...

In [57]:
arr1 = np.arange(24).reshape(2, 3, 4)
print("arr1: \n",arr1)

arr1: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [58]:
for zero_axis in arr1:
    print("Iteration:")
    print(zero_axis)

Iteration:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Iteration:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


**Example 5:** If you want to iterate on *all* elements in the `ndarray`, simply iterate over the `flat` attribute:

In [59]:
arr1 = np.arange(12).reshape(3, 4)
print("arr1: \n",arr1)

arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
for i in arr1.flat:
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

# Part-II (Manipulating Array Elements)

## Learning agenda 

1. Updating existing values of NumPy array elements
2. Append new elements to a NumPy array using np.append()
3. Insert new elements in a NumPy array using np.insert()
4. Delete elements of a NumPy array using np.delete()
5. Alias vs Shallow Copy vs Deep Copy

## 1. Updating Existing Values of Numpy Array Elements

### a. 1-D Arrays

In [61]:
arr = np.random.randint(low = 1, high = 100, size = 10)
print("Original Array \n", arr)
arr[2] = 333
arr[-1] = 777
print("Updated Array \n", arr)

Original Array 
 [56 68  2 86 72 45 14 73 48 45]
Updated Array 
 [ 56  68 333  86  72  45  14  73  48 777]


### b. 2-D Arrays

In [62]:
# Creating 2-D array of size 4x4 of int type b/w interval 1 to 9
arr = np.random.randint(low = 1, high = 10, size = (4, 4))
print("Original Array \n", arr)
arr[0][1] = 77
arr[1][2] = 66
arr[2][-1] = 22
print("Updated Array \n", arr)

Original Array 
 [[4 8 3 1]
 [9 2 5 3]
 [9 9 7 1]
 [4 9 3 7]]
Updated Array 
 [[ 4 77  3  1]
 [ 9  2 66  3]
 [ 9  9  7 22]
 [ 4  9  3  7]]


## 2. Append New Elements to Numpy Arrays
- The `np.append()` method allows us to insert new values at the end of a NumPy array.
- The method always returns a copy of the existing numpy array with the values appended to the given axis.
```
np.append(arr, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to append
    - `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is specified, then `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
- The original array remains as such, as it does not occur in-place.

### a. Appending Elements in 1-D Arrays

In [63]:
arr1 = np.random.randint(low = 1, high = 100, size = 10)
print("arr1 = ", arr1)

arr1 =  [22 74 81 40 49 82 93 71  8 44]


In [64]:
# You can add a scalar value or a list of values at the end of a 1-D array
arr2 = np.append(arr1, [101, 202,303])
print("After append:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After append:
arr1 =  [22 74 81 40 49 82 93 71  8 44]
arr2 =  [ 22  74  81  40  49  82  93  71   8  44 101 202 303]


In [65]:
print(id(arr1))
print(id(arr2))

1862237709168
1862237709648


### b. Appending Elements in 2-D Arrays

**Example:** In case of 2-D Arrays if `axis` is not mentioned both `arr` and `values` are flattened before use

In [66]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[9 6 1]
 [5 7 3]
 [8 9 4]]


In [67]:
# If the axis is not mentioned, values can be of any shape and both `arr` and `values` are flattened before use.
arr2 = np.append(arr1, [101, 202,303, 404, 505])
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After append:
arr1 = 
 [[9 6 1]
 [5 7 3]
 [8 9 4]]
arr2 =  [  9   6   1   5   7   3   8   9   4 101 202 303 404 505]


**Example:** Appending a Row to a 2-D array (`axis=0`)

In [68]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,3))
print("arr1 = \n", arr1)
print("shape: ", arr1.shape)

arr1 = 
 [[1 9 8]
 [2 1 7]
 [8 8 1]
 [7 9 4]]
shape:  (4, 3)


In [69]:
# For appending at axis 0, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a row vector, and in this case of shape (1,3), having 1 row and 3 columns
arr2 = np.append(arr1, [[101, 202,303]], axis=0)
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After append:
arr1 = 
 [[1 9 8]
 [2 1 7]
 [8 8 1]
 [7 9 4]]
arr2 = 
 [[  1   9   8]
 [  2   1   7]
 [  8   8   1]
 [  7   9   4]
 [101 202 303]]


**Example:** Appending a Column to a 2-D array (`axis=1`)

In [70]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,3))
print("arr1 = \n", arr1)
print("shape: ", arr1.shape)

arr1 = 
 [[2 2 6]
 [1 1 7]
 [5 5 2]
 [5 6 8]]
shape:  (4, 3)


In [71]:
# For appending at axis 1, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a column vector of shape (4,1), having 4 rows and 1 column
arr2 = np.append(arr1, [[101], [202], [303], [404]], axis=1)
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After append:
arr1 = 
 [[2 2 6]
 [1 1 7]
 [5 5 2]
 [5 6 8]]
arr2 = 
 [[  2   2   6 101]
 [  1   1   7 202]
 [  5   5   2 303]
 [  5   6   8 404]]


## 3. Inserting New Elements in Numpy Arrays
- The `np.insert()` method allows us to insert new values along the given axis before the given index.
- The method always returns a copy of the existing numpy array with the values inserted to the given axis.
```
np.insert(arr, index, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to insert
    - `index` is the index before which we want to insert
    - `values` [array_like] values to be added in the `arr`
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is zero, a row is inserted (For 2-D arrays)
    - If `axis` is one, a column is inserted (For 2-D arrays)
- The original array remains as such, as it does not occur in-place.

### a. Inserting Elements in 1-D Arrays

In [72]:
arr1 = np.random.randint(low = 1, high = 100, size = 5)
print("arr1 = ", arr1)

arr1 =  [92 25 19 72 48]


In [73]:
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 3, [55, 66,77])
print("After insert:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After insert:
arr1 =  [92 25 19 72 48]
arr2 =  [92 25 19 55 66 77 72 48]


### b. Inserting Elements in 2-D Arrays

**Example:** In case of 2-D array, if `axis` is not mentioned the array is flattened first

In [74]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[2 4 3 7]
 [7 5 2 2]
 [6 5 9 2]]


In [75]:
# Inserting a single value
arr2 = np.insert(arr1, 4, 55)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After insert:
arr1 = 
 [[2 4 3 7]
 [7 5 2 2]
 [6 5 9 2]]
arr2 =  [ 2  4  3  7 55  7  5  2  2  6  5  9  2]


In [76]:
# Inserting a multiple values
arr2 = np.insert(arr1, 4, [55, 66])
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After insert:
arr1 = 
 [[2 4 3 7]
 [7 5 2 2]
 [6 5 9 2]]
arr2 =  [ 2  4  3  7 55 66  7  5  2  2  6  5  9  2]


**Example:** If axis=0, value(s) are added as a row before mentioned index

In [77]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[2 7 5 9]
 [3 6 7 1]
 [6 7 2 6]]


In [78]:
# For axis = 0, note how the scalar value is replicated before insertion
arr2 = np.insert(arr1, 2, 55, axis=0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[2 7 5 9]
 [3 6 7 1]
 [6 7 2 6]]
arr2 = 
 [[ 2  7  5  9]
 [ 3  6  7  1]
 [55 55 55 55]
 [ 6  7  2  6]]


In [79]:
# For axis=0, note the size of values has to be 4 in this case (equal to number of columns)
arr2 = np.insert(arr1, 2, [55, 66, 77, 88], axis=0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[2 7 5 9]
 [3 6 7 1]
 [6 7 2 6]]
arr2 = 
 [[ 2  7  5  9]
 [ 3  6  7  1]
 [55 66 77 88]
 [ 6  7  2  6]]


**Example:** If axis=1, value(s) are added as a column at mentioned index

In [80]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[9 8 5 2]
 [3 9 8 5]
 [2 4 2 7]]


In [81]:
# For axis = 1, note how the scalar value is replicated before insertion
arr2 = np.insert(arr1, 2, 55, axis=1)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[9 8 5 2]
 [3 9 8 5]
 [2 4 2 7]]
arr2 = 
 [[ 9  8 55  5  2]
 [ 3  9 55  8  5]
 [ 2  4 55  2  7]]


In [82]:
# For axis=1, note the size of values has to be 3 in this case (equal to number of rows)
arr2 = np.insert(arr1, 2, [55, 66, 77], axis=1)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[9 8 5 2]
 [3 9 8 5]
 [2 4 2 7]]
arr2 = 
 [[ 9  8 55  5  2]
 [ 3  9 66  8  5]
 [ 2  4 77  2  7]]


## 4. Deleting  Elements of Numpy Arrays
- The `np.delete()` method allows us to delete value(s) from an array at the given index
- This function always returns a copy of the existing numpy array with the values deleted from the given axis.
- If axis is not specified, values can be of any shape and will be flattened before use
```
np.delete(arr, index, axis=None)
```
- The original array remains as such, as it does not occur in-place.

In [83]:
### a. Deleting Elements from a 1-D Arrays

**Example:**

In [84]:
arr1 = np.random.randint(low = 1, high = 10, size = 5)
print("arr1 = ", arr1)

arr1 =  [7 8 5 3 4]


In [85]:
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, 3)
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After delete:
arr1 =  [7 8 5 3 4]
arr2 =  [7 8 5 4]


**Example:**

In [86]:
arr1 = np.random.randint(low = 1, high = 100, size = 10)
print("arr1 = ", arr1)

arr1 =  [75 99 69 50  4 99 27 59 53 55]


In [87]:
# You can delete a list of values in between array elements from specific indices
arr2 = np.delete(arr1, [2,5])
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After delete:
arr1 =  [75 99 69 50  4 99 27 59 53 55]
arr2 =  [75 99 50  4 27 59 53 55]


### b. Deleting Elements from a 2-D Arrays

**Example:** Delete a specific element from a 2-D array, don't mention the axis. The resulting array is flattened before use

In [88]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[9 6 4]
 [3 8 5]
 [7 6 8]]


In [89]:
arr2 = np.delete(arr1, 5)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After delete:
arr1 = 
 [[9 6 4]
 [3 8 5]
 [7 6 8]]
arr2 =  [9 6 4 3 8 7 6 8]


**Example:**  Delete a specific row from an existing 2-D array

In [90]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,4))
print("arr1 = \n", arr1)

arr1 = 
 [[6 7 7 5]
 [6 3 9 9]
 [2 1 9 7]
 [8 9 4 2]]


In [91]:
arr2 = np.delete(arr1, 2, axis=0)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After delete:
arr1 = 
 [[6 7 7 5]
 [6 3 9 9]
 [2 1 9 7]
 [8 9 4 2]]
arr2 = 
 [[6 7 7 5]
 [6 3 9 9]
 [8 9 4 2]]


**Example:**  Delete a specific column from an existing 2-D array

In [92]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,4))
print("arr1 = \n", arr1)

arr1 = 
 [[6 3 4 3]
 [2 1 3 3]
 [1 3 6 6]
 [6 1 9 2]]


In [93]:
arr2 = np.delete(arr1, 2, axis=1)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After delete:
arr1 = 
 [[6 3 4 3]
 [2 1 3 3]
 [1 3 6 6]
 [6 1 9 2]]
arr2 = 
 [[6 3 3]
 [2 1 3]
 [1 3 6]
 [6 1 2]]


## 5. Assigning vs Coping NumPy Arrays

### a. Assigning two NumPy Arrays (Create an alias)

In [94]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Creating a copy using assignment operator, both variables point at the same array
arr2 = arr1

print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [4 8 1 3 9 6 2 5 2 7]
arr2 =  [4 8 1 3 9 6 2 5 2 7]
1862237704656
1862237704656


In [95]:
# Change value in arr1 will also occur in arr2
arr2[2] = 55
print("arr1 = ", arr1)
print("arr2 = ", arr2)


arr1 =  [ 4  8 55  3  9  6  2  5  2  7]
arr2 =  [ 4  8 55  3  9  6  2  5  2  7]


### b. View/Shallow Copy
Arrays that share some data. The view method creates an object looking at the same data. Slicing an array returns a view of that array.

In [96]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Creating a shallow copy (view) using slice operator
arr2 = arr1[:]

print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [5 1 1 4 5 4 2 5 7 1]
arr2 =  [5 1 1 4 5 4 2 5 7 1]
1862237711184
1862237710800


In [97]:
# Change value in arr1 will occur in arr2
arr2[2] = 55

print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [ 5  1 55  4  5  4  2  5  7  1]
arr2 =  [ 5  1 55  4  5  4  2  5  7  1]


### c. Deep Copy

In [98]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Create a Deep copy using copy() method, which will create a new copy of the array
arr2 = arr1.copy()
print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [1 8 3 5 1 5 3 9 6 1]
arr2 =  [1 8 3 5 1 5 3 9 6 1]
1862237711280
1862237704656


In [99]:
# Change value in array 1 will NOT occur in array 2
arr2[2] = 55

print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [1 8 3 5 1 5 3 9 6 1]
arr2 =  [ 1  8 55  5  1  5  3  9  6  1]
