# Part -I (NumPy-Array Creation)

# Learning agenda 
1. Introduction to Numpy Library
2. Array Creation using `np.array()` constructor
3. Miscellaneous Array Creation Functions
    - `np.zeros()`
    - `np.ones()`
    - `np.empty()`
    - `np.full()`
    - `np.eye()`
    - `np.fromstring()`
    - `np.arange()`
    - `np.linspace()`
    - `np.random.rand()`
    - `np.random.randint()`
    - `np.zeros_like()`

## 1. Introduction to Numpy Library

- *A **NumPy array** (https://numpy.org) is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.*
- Some attributes of NumPy Array:
>- **ndim:** The number of dimensions, can be 1, 2, 3, ... N
>- **axis:** Each dimension is called an axis: `axis 0` is the vertical axis, goes from top to bottom, represents the number of rows, `axis 1` is the horizontal axis, goes from left to right, represents the number of columns, `axis 2` is the number of columns along z axis
>- **rank:** The number of axes is called the rank.
>- **shape:** It is a tuple whose length is the rank and elements are dimension of each axis.
>- **size:** It is the total number of elements, which is the product of all axis lengths.
>- **itemsize:** It gives you the size in bytes of each element of the array (depends on dtype).
>- **nbytes:** It gives you the total number of bytes occupied by entire array object in memory (size x itemsize).

To understand the internal memory layout of NumPy ndarray object, consider the four additional attributes:
- A pointer, to block of data in RAM or in a memory-mapped file
- A dtype, that describes fixed-size value cells in the array
- A shape, which is a tuple indicating the array’s shape
- A strides, which is a tuple of integers indicating the number of bytes to “step” in order to advance one element along a dimension (C-Type/Row-Major vs F-Type/Column-Major)
    - Row-Major means that if you have a two-dimensional array of data, the values in each row of the array are stored in adjacent memory locations
    - Column-Major means that if you have a two-dimensional array of data, the values in each column of the array are stored in adjacent memory locations
    
    
    
>- **data:** A pointer to block of data in RAM or in memory-mapped file. (Returns memory address)
>- **dtype:** It gives you the dtype of the numPy array elements (fixed size value cells in memory)
>- **shape:** It gives you a tuple indicating the array's shape
>- **strides:** The strides attribute is a tuple of the same length as the number of axes (dimensions) of the array. The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, in above 2-D array (shown in figure), we have to skip 4 bytes (1 value) to move to the next column, but 12 bytes (3 values) to get to the same position in the next row (for row-major).
    - Row-Major means that if you have a two-dimensional array of data, the values in each row of the array are stored in adjacent memory locations
    - Column-Major means that if you have a two-dimensional array of data, the values in each column of the array are stored in adjacent memory locations
>- **flags:** It gives you information about the memory layout of the array.

In [1]:
import sys
!{sys.executable} -m pip install --upgrade pip

In [2]:
# Unlike the other modules, we have been working so far, you have to download and install numPy
# To install this library in Jupyter notebook
import sys
!{sys.executable} -m pip install numpy

In [3]:
import numpy as np
np.__version__ , np.__path__

('1.26.4', ['C:\\Users\\attari\\anaconda3\\Lib\\site-packages\\numpy'])

## 2.  Array Creation using `np.array()` Constructor
```
np.array(seq, dtype)
```
- The only required argument is a sequence like object like a list from which to create an array
- The optional `dtype` argument specifies the data type of the array objects. 
- For integer values it is normally int64
- For float values it is normally float64.
- You can mention `dtype` if you want to limit memory usage. 

In [4]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

### a.  Creating an Empty NumPy Array

In [5]:
import numpy as np
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [6]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  []
arr.ndim:  1
arr.shape:  (0,)
arr.size:  0
arr.dtype:  float64
arr.itemsize:  8
arr.nbytes:  0
arr.data:  <memory at 0x00000204B50A13C0>
arr.strides:  (0,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### b.  0-Dimensional Array
- A 0-D array has a single scalar value, and has zero or no axis

In [7]:
# Create a 0-D numpy array using array() constructor
import numpy as np
arr = np.array(10)
print("array: ", arr)

array:  10


In [8]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (a 0-D array has number of dimensions equals to 0)
print("arr.shape: ", arr.shape) # This is a scalar value, so have no shape ( )
print("arr.size: ", arr.size)   # get total number of elements, in this case it is 1
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the only element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for int64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  10
arr.ndim:  0
arr.shape:  ()
arr.size:  1
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  4
arr.data:  <memory at 0x00000204B52A98A0>
arr.strides:  ()
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### c.  1-Dimensional Arrays
- An array that has 0-D arrays or scalar values, as its elements is called a 1-D array. 
- Used to represent vectors or 1st order tensors.
- A 1-D array has only one axis:
    - **axis 0:** or vertical axis   or x-axis or number of rows

In [9]:
arr = np.array([[5,3,2],[8,9,-1],[2,-3,6]])
arr

array([[ 5,  3,  2],
       [ 8,  9, -1],
       [ 2, -3,  6]])

In [10]:
for i in range(3):
    for j in range(3):
        print(arr[i,j])

5
3
2
8
9
-1
2
-3
6


# 

In [11]:
# Create a 1-D numpy array using array() constructor of numpy

mylist = [1, 4, 2, 5, 3]
arr = np.array(mylist, dtype=np.uint8)
arr = np.array([1, 4, 2, 5, 3], dtype=np.uint32)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint32
arr.itemsize:  4
arr.nbytes:  20
arr.data:  <memory at 0x00000204B50A1840>
arr.strides:  (4,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



>Note once you print NumPy array elements they are displayed inside `[ ]` as a Python List, however, the elements are space separated in case of NumPy arrays, while in case of Python Lists the elements are comma separated

### d.  2-Dimensional Arrays

- An array that has 1-D arrays as its elements is called a 2-D array. 
- Used to represent matrix or 2nd order tensors.
- A 2-D array has two axis:
    - **axis 0:** is the vertical axis, goes from top to bottom, represents the number of rows (5)
    - **axis 1:** is the horizontal axis, goes from left to right, represents the number of columns (4)
- If you've taken a linear algebra class in high school, you may recognize this 2-d array as a matrix with five rows and four columns. 
- Each row represents a city, and the columns may contain temperature, rainfall, humidity, and smog in that city respectively.

In [12]:
# creating 2-D (5x4) array using array constructor in numpy

mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.dtypes: ", arr.dtype)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]
arr.ndim:  2
arr.shape:  (5, 4)
arr.size:  20
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  80
arr.data:  <memory at 0x00000204B5761150>
arr.dtypes:  int32
arr.strides:  (16, 4)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [13]:
arr[1][1]
arr[1,1]

6

In [14]:
# Another example
mylist = [[1], [4], [2], [5], [3]]
arr = np.array(mylist)
arr = np.array([[1], [2], [3]])
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1]
 [2]
 [3]]
arr.ndim:  2
arr.shape:  (3, 1)
arr.size:  3
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  12
arr.data:  <memory at 0x00000204B5764AD0>
arr.strides:  (4, 4)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### e.  3-Dimensional Arrays

- An array that has 2-D arrays as its elements is called a 3-D array. Used to represent 3rd order tensors.
- A 3-D array has three axis:
    - **axis 0:** represent the number of rows along x-axis(axis 0). (5)
    - **axis 1:** represents the number of rows along y-axis (axis 1). (4)
    - **axis 2:** represents the number of columns along z-axis (axix 2). (3)

In [15]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist, dtype=np.uint8)


print("array: \n", arr)
print("arr.ndim: ", arr.ndim)    # get number of dimensions (3-D array)
print("arr.shape: ", arr.shape)  # get dimension size.For a 3-D array, return a tuple with three elements
print("arr.size: ", arr.size)    # get total number of elements (5*4*3=60 elements)
print("arr.dtype: ", arr.dtype)  # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*60=4800)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]
arr.ndim:  3
arr.shape:  (5, 4, 3)
arr.size:  60
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  60
arr.data:  <memory at 0x00000204B52B4B80>
arr.strides:  (12, 3, 1)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Understanding Strides

In [16]:
# Strides of 1-D array
import numpy as np
mylist = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[3]) # jump 3*8=24 bytes and then read 8 bytes

array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.data:  <memory at 0x00000204B50A1840>
arr.shape:  (12,)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (8,)
3


In [17]:
# Strides of 2-D array
import numpy as np
mylist = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,2]) # jump 1*32+2*8=48 bytes and then read 8 bytes

array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.data:  <memory at 0x00000204B5770790>
arr.shape:  (3, 4)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 8)
6


In [18]:
# Strides of 3-D array
import numpy as np
mylist = [
          [[0, 1], [2, 3]],
          [[4, 5], [6, 7]],
          [[8, 9], [10, 11]]
         ]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,1,1]) # jump 1*32 + 0*16 + 1*8 =40 bytes and then read 8 bytes

array: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
arr.data:  <memory at 0x00000204B52B5300>
arr.shape:  (3, 2, 2)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 16, 8)
7


## 3. Miscellaneous Array Creation Function
- Numpy also provides some handy methods to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

<img align="right" width="150" height="100"  src="images/zeros.png"  > 

### a. Using `np.zeros()` Method
This method returns an array of given shape and type, filled with zeros.

```
numpy.zeros(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [19]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3)
arr
# Notice that the elements are having the default data type as the float. That’s why the zeros are 0.

array([0., 0., 0.])

In [20]:
# Creating 2-Dimensional array filled with zeros
arr = np.zeros((2,3))
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Creating 2-Dimensional array filled with zeros of integer types
arr = np.zeros((2,3), dtype=np.int16)
arr, arr.nbytes

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 12)

### b. Using `np.ones()` Method
This method returns an array of given shape and type, filled with ones.
```
numpy.ones(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [22]:
# Creating one-dimensional array with ones
arr = np.ones(3)
arr


array([1., 1., 1.])

In [23]:
# Creating 2-Dimensional array having 3 columns filled with ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Creating 2-Dimensional array having 3 columns filled with ones of integer types
arr = np.ones((2,3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)


### c. Using `np.empty()` Method
This method returns an array of given shape and type, filled with junk values.

```
numpy.empty(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.


Un-like numpy.zeros(), and numpy.ones(), the numpy.empty() function doesn't initialize the entries, so they contain junk values.

In [25]:
arr = np.empty(3)
arr

array([1., 1., 1.])

In [26]:
arr = np.empty(3, dtype=np.int16)
arr

array([257, 257, 257], dtype=int16)

In [27]:
# Creating 2-Dimensional array having 3 columns filled with junk values
arr = np.empty((2,3), dtype=np.int16)
arr

array([[-1, -1, -1],
       [-1, 23,  0]], dtype=int16)


### d. Using `np.full()` Method
This method return a new array of given shape and type, filled with fill_value.
```
np.full(shape, fill_value, dtype=None)
```
- shape: Shape of the new array
- fill_value: Fill value.
- dtype	The desired data-type for the array

In [28]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [29]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [30]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])


### e. Using `np.eye()` Method
This method is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

```
eye(N, M=None, k=0 , dtype=float)
```
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
- dtype: Data-type of the returned array

In [31]:
# creating 2-D array using eye function
# with 2 rows and 2 columns having 1's at on the main diagonal
eye_arr = np.eye(3,3)
eye_arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at on the main diagonal
eye_arr = np.eye(4, 3, dtype=np.int8)
eye_arr


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)

In [33]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4, 3, k = 1, dtype=int)
eye_arr

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place lower
eye_arr = np.eye(4, 3, k = -1, dtype=int)
eye_arr

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])


### f. Using `np.fromstring()` Method
This function is used to create a new 1-D array initialized from raw binary or text data in a string.
```
np.fromstring(string, dtype, sep)
```
- string: A string containing the data
- dtype: The data type of the array (by default float)
- sep: The string separating numbers in the data

In [35]:
# convert the space separated string '25 30 35 40' into an floats array
arr = np.fromstring('25 30 35 40', sep=' ')
arr

array([25., 30., 35., 40.])

In [36]:
# convert the space separated string '25 30 35 40' into an integer array
arr = np.fromstring('25 30 35 40', sep=' ', dtype=np.uint8)
arr

array([25, 30, 35, 40], dtype=uint8)

In [37]:
# converting comma separated string into float type array
arr = np.fromstring('0.7, 10.4, 50.5', sep=",")
print(arr)


[ 0.7 10.4 50.5]


In [38]:
# It will raise error
arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')

C:\Users\attari\AppData\Local\Temp\ipykernel_9068\1942666505.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')


### g. Using `np.arange()` Method
This function is used to get evenly spaced values within a given interval.

```
numpy.arange([start,] stop[, step])
```
- If only one argument is given will generate an int64 array from zero to that value (not inclusive)
- If two arguments are given then start value in inclusive, stop value is not inclusive and the default step is 1
- If three arguments are given then the third argument is the distance between two adjacent values. (default step size is 1)
- All the three arguments can be integers or floats

The image shows the array created by np.arange(5,9,1)


In [39]:
import numpy as np
arr = np.arange(5)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
int32


In [40]:
arr = np.arange(5, dtype=float)
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4.]
float64


In [41]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [42]:
arr = np.arange(5, 10, 2)
arr

array([5, 7, 9])

In [43]:
arr = np.arange(5, 15, -1)
arr

array([], dtype=int32)

In [44]:
arr = np.arange(-1, -4, -.5)
arr

array([-1. , -1.5, -2. , -2.5, -3. , -3.5])

### h. Using `np.linspace()` Method
This method by default returns an array of 50 evenly spaced elements starting from the first argument (inclusive) to the second argument (inclusive). The third argument, if given, is the count of number of elements of the array, default is 50.

```
numpy.linspace(start, stop, num=50)
```

In [45]:
arr = np.linspace(2,3,4)
print(arr)
print(arr.dtype)

[2.         2.33333333 2.66666667 3.        ]
float64


In [46]:
arr = np.linspace(1,2)
print(arr)
print(arr.dtype)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
float64


In [47]:
arr = np.linspace(-1,-5)
print(arr)

[-1.         -1.08163265 -1.16326531 -1.24489796 -1.32653061 -1.40816327
 -1.48979592 -1.57142857 -1.65306122 -1.73469388 -1.81632653 -1.89795918
 -1.97959184 -2.06122449 -2.14285714 -2.2244898  -2.30612245 -2.3877551
 -2.46938776 -2.55102041 -2.63265306 -2.71428571 -2.79591837 -2.87755102
 -2.95918367 -3.04081633 -3.12244898 -3.20408163 -3.28571429 -3.36734694
 -3.44897959 -3.53061224 -3.6122449  -3.69387755 -3.7755102  -3.85714286
 -3.93877551 -4.02040816 -4.10204082 -4.18367347 -4.26530612 -4.34693878
 -4.42857143 -4.51020408 -4.59183673 -4.67346939 -4.75510204 -4.83673469
 -4.91836735 -5.        ]


### i. Using `np.random.rand()` Method
- This method generates an array of random floats (between 0 and 1) of as many dimensions passed as argument.
- If no argument is passed, generates a scalar value between 0 and 1

```
numpy.random.rand(d0 [,d1] [,d2]....)
```


In [48]:
#Python's built-in random module has random() function that returns a single float between 0 and 1
import numpy as np
value = np.random.rand()
value

0.7846836589981265

In [49]:
# Creating 1-D array of 5 elements of random floats between 0 and 1
arr = np.random.rand(5)
arr


array([0.44393596, 0.94321408, 0.49134753, 0.74703605, 0.85211397])

In [50]:
# Creating 1-D array of 5 elements of random floats between 0 and 10
arr = np.random.rand(5)*10
arr


array([4.86441056, 2.05743288, 9.56149538, 2.99376098, 5.96234373])

In [51]:
# Creating 2-D array (4x3) having random floats between 0 and 1
arr = np.random.rand(4,3)*10
arr

array([[2.27199159, 1.65300657, 8.21448553],
       [5.3600307 , 6.38395185, 2.47465851],
       [1.63443063, 6.04001365, 6.85336112],
       [3.13840604, 3.00828903, 9.38406097]])

In [52]:
# Creating 2-D array (4x3) having random floats between 0 and 10
arr = np.random.rand(4,3)*10
arr

array([[3.14137007, 6.25659339, 0.05583692],
       [1.1344055 , 4.55616242, 4.10981453],
       [9.07866166, 9.99009438, 5.48263382],
       [8.63873133, 7.30810858, 7.55799197]])

In [53]:
# Creating 3-D array of with random values using np.random.rand()
arr = np.random.rand(5,4,3)
arr

array([[[0.25316721, 0.69927487, 0.9784805 ],
        [0.59255519, 0.66868921, 0.81497938],
        [0.40326111, 0.97472644, 0.17264312],
        [0.62898489, 0.56857358, 0.20453976]],

       [[0.8139417 , 0.77244762, 0.27323267],
        [0.80457217, 0.90071466, 0.10149768],
        [0.32197175, 0.39476922, 0.08730004],
        [0.56983851, 0.0959149 , 0.96049376]],

       [[0.09310193, 0.46889568, 0.08904162],
        [0.52065174, 0.14533154, 0.55701221],
        [0.02322843, 0.09928902, 0.48167775],
        [0.86384754, 0.96007703, 0.36742588]],

       [[0.4722883 , 0.36304987, 0.44085591],
        [0.5709554 , 0.56444155, 0.0663499 ],
        [0.83289373, 0.61138188, 0.24321385],
        [0.78939282, 0.89735163, 0.2588816 ]],

       [[0.12225774, 0.22919843, 0.9710184 ],
        [0.67320733, 0.29567481, 0.97840102],
        [0.62162154, 0.08293908, 0.54516239],
        [0.23994389, 0.60025072, 0.95572769]]])

### i. Using `np.random.randint()` Method
This method returns an array of specified shape and fills it with random integers.
```
numpy.random.randint(low, high=None, size)
```
- low: Lowest (signed) integer to be drawn from the distribution. But, it works as a highest integer in the sample if high=None.
- high: Largest (signed) integer to be drawn from the distribution (not inclusive)
- size: number of samples to be generated (default is 1 for scalar and >1 for 1-D array and a tupple for ndarray)

In [54]:
# Generating a random integer scalar b/w interval (0,9) 
value = np.random.randint(10)
value

5

In [55]:
# Generating a random integer scalar b/w interval (5,19) 
value = np.random.randint(low=5, high=20)
value

5

In [56]:
# Generating a random integer scalar from -5 to 4 
value = np.random.randint(low=-5, high=5)
value

3

In [57]:
# creating 1-D array of size 6 of int type b/w interval (1,100) 
arr = np.random.randint(low=1, high=101, size=6)
arr

array([85, 79, 69, 35, 29, 56])

In [58]:
# creating 1-D array of size 6 of int type b/w interval (-5,4) 
arr = np.random.randint(low = -5, high = 5, size = 4)
arr

array([ 4, -3,  3,  3])

In [59]:
# By passing a tuple to size means rows and columns
arr = np.random.randint(low = 1, high = 10, size = (3,3))
arr

array([[1, 8, 7],
       [1, 1, 2],
       [6, 3, 5]])

In [60]:
arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

array([[[7, 3, 1, 5],
        [4, 9, 9, 7],
        [5, 1, 6, 1]],

       [[6, 8, 4, 9],
        [5, 1, 7, 9],
        [9, 1, 4, 6]]])


### k. Using `np.zeros_like()` Method
This method is used to get an array of zeros with the same shape and type as a given array.

```
zeros_like(arr, dtype=None) 
```

- arr: array like input
- dtype: Overrides the data type of the result

In [61]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)


A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]


In [62]:
# creating 1-D array
arr1 = np.arange(10)
print("A 1-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)


A 1-D array 
 [0 1 2 3 4 5 6 7 8 9]

 Converted Array 
 [0 0 0 0 0 0 0 0 0 0]


In [63]:
np.fromstring

<function numpy.fromstring>

In [64]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Part -II (Array vs List)

# Learning agenda 
1. A Comparison
    - Python Lists
    - Python Arrays
    - NumPy Arrays
2. Memory Consumption of Python List and Numpy Array
3. Operation cost on Python List and Numpy Array

### a. Python Lists
- Python List is a numerically ordered sequence of elements that can store elements of heterogeneous types, is iterable, mutable and allows duplicate elements.
- A Python List is built-in type in Python and can be created by placing comma separated values in square brackets, and you don't have to specify the type while creating a Python List
- Python list is by default 1 dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
- Items are stored non-contiguously in memory.
- More memory hungry.
- Operations on Lists are typically slower, however, append operation will take O(1) time.

In [65]:
# creating a list containing elements belonging to different data types  
mylist = [1, "Data Science", ['a','e'], False, 5.72]  
print(mylist) 
print(type(mylist))

[1, 'Data Science', ['a', 'e'], False, 5.72]
<class 'list'>


### b. Python Arrays
- A simple Python array is a sequence of objects of similar data dype. Python array module requires all array elements to be of the same type. Moreover, to create an array, you'll need to specify a value type. 

```
array(typecode [, initializer])
```

- Return a new array whose items are restricted by typecode, and initialized from the optional initializer value, which must be a list, string or iterable over elements of the appropriate type.

- Arrays represent basic values and behave very much like lists, except the type of objects stored in them is constrained. The type is specified at object creation time by using a type code, which is a single character.
- The following type codes are defined:


    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
    'q'         signed integer     8 (see note)
    'Q'         unsigned integer   8 (see note)
    'f'         floating point     4
    'd'         floating point     8

In [66]:
# To use Python arrays, you have to import Python's built-in array module
import array

# declaring array of integers
arr1 = array.array('i', [3, 6, 9, 2])  
print(arr1)  
print(type(arr1))  

# declaring array of floats
arr2 = array.array("f", [3.4, 6.7, 9.5, 2])  
print(arr2)  
print(type(arr2))  

# Python arrays can grow/shrink dynamically
arr2.append(999)
print(arr2)

array('i', [3, 6, 9, 2])
<class 'array.array'>
array('f', [3.4000000953674316, 6.699999809265137, 9.5, 2.0])
<class 'array.array'>
array('f', [3.4000000953674316, 6.699999809265137, 9.5, 2.0, 999.0])


### c. Numpy Arrays
- A NumPy array is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.
- NumPy arrays have a fixed size at creation, unlike Python lists/arrays (which can grow dynamically). If you change the size of a numPy array, it will create a new array and delete the original. 
- NumPy arrays are less memory hungry and offer better performance than Python Lists.



**Differences between Python List and NumPy Arrays:**
1. Lists are part of core Python. Arrays are not part of core Python
2. Lists can contain elements of different types. An Array’s elements must all be of the same type
3. Lists don’t need to be declared. Arrays need to be declared before use.
4. Arrays (in Numpy) are optimized for fast mathematical operations. Lists are not.
5. Arrays are optimized for storage (which is why you need to declare them before use). Lists are not.
6. Lists can grow/shrink and are more flexible (they allow easy extension or reduction by adding/deleting elements). Arrays are not flexible.


- In general if you are going to make heavy use of mathematical operations, or need to store and process a large amount of numerical data, you should go with arrays rather than lists. If you are also particular about efficient memory storage, you should use arrays.

In [67]:
# NumPy array upcast data type of all elements to bigger datatype in case of different types
import numpy as np
array1 = np.array([3.5, True, 9, 2.7, False])
print(array1)
print(type(array1))
print(type(array1[1]))

[3.5 1.  9.  2.7 0. ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [68]:
# NumPy array upcast data type of all elements to bigger datatype in case of different types
import numpy as np
array1 = np.array([3.5, 9, 2.7, 'arif', False])
print(array1)
print(type(array1))
print(type(array1[1]))

['3.5' '9' '2.7' 'arif' 'False']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [69]:
# If you mention the data type, the elements are automatically typecasted to the mentioned type
import numpy as np
array1 = np.array([3.5, False, 9.8, 2.7, True], dtype=np.uint16)
print(array1)
print(type(array1))
print(type(array1[1]))

[3 0 9 2 1]
<class 'numpy.ndarray'>
<class 'numpy.uint16'>


## 2. Memory Consumption of NumPy Array and Python List
- Python Lists consume more memory than NumPy arrays

In [71]:
import numpy as np
import sys
  
# declaring a list of 1000 elements 
list1 = range(1000)

element_size = sys.getsizeof(list1)
list1_size = element_size * len(list1)
print("Size of each element = {} and Size of list1 = {} bytes".format(element_size, list1_size))
  
# declaring a Numpy array of 1000 elements 
array1 = np.arange(1000, dtype=np.uint8)
print("\nSize of each element = {} and Size of array1 = {} bytes".format(array1.itemsize, array1.nbytes))

Size of each element = 48 and Size of list1 = 48000 bytes

Size of each element = 1 and Size of array1 = 1000 bytes


## 3. Operations on NumPy Arrays vs Python Lists
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. 
- This behavior is called **locality of reference** in computer science. 
- This is the main reason why NumPy is faster than lists. 
- As a proof of concept, we can multiply two list and and then two arrays, and compare their multiplication time

### Effect of * operator on NumPy Array and Python List

In [72]:
# You can multiply two numPy arrays using * operator
import numpy as np
myarray1 = np.array([1, 2, 3, 4, 5, 6])
myarray2 = np.array([1, 2, 3, 4, 5, 6])
myarray3 = myarray1 * myarray2
myarray3

array([ 1,  4,  9, 16, 25, 36])

In [73]:
# you can't multiply two lists using a * operator, you have to use a loop
mylist1 = [1, 2, 3, 4, 5, 6]
mylist2 = [1, 2, 3, 4, 5, 6]
mylist3 = [0, 0, 0, 0, 0, 0]
for i in range(0,6):
    mylist3[i] = mylist1[i] * mylist2[i]
mylist3

[1, 4, 9, 16, 25, 36]

**Let us calculate time to multiply two numPy arrays of 1 million elements**

In [74]:
import time
size = 1000000
array1 = np.arange(size)
array2 = np.arange(size)

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
array3 = array1 * array2

# capturing time again after the multiplication is done
finishTime = time.time()

print("\nTime taken by NumPy Arrays to perform multiplication:", finishTime - initialTime, "seconds")



Time taken by NumPy Arrays to perform multiplication: 0.003231048583984375 seconds


**Let us calculate time to multiply two Python Lists of 1 million elements**

In [75]:
import time

# Creating two large size Lists and multiplying them element by element
list1 = list(range(size))
list2 = list(range(size))
list3 = list(range(size))

# capturing time before the multiplication of Python Lists
initialTime = time.time()

# multiplying elements of both the lists and stored in another list
# simply run a loop and overwrite the elements of the new list with resulting value
for i in range(0, len(list1)):
     list3[i] = list1[i] * list2[i]


# capturing time again after the multiplication is done
finishTime = time.time()

print("\nTime taken by Lists to perform multiplication:", finishTime - initialTime, "seconds")


Time taken by Lists to perform multiplication: 0.41883325576782227 seconds
