# Part -I (Basic Operations on NumPy Arrays)

## Learning agenda 
- Operations on numPy arrays are done element-wise. This means that you don't explicitly have to write for-loops in order to do these operations!
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.
1. Scalar Math
    - On 1-D Arrays
    - On 2-D Arrays
2. Arithmetic operations
    - On 1-D Arrays
    - On 2-D Arrays
3. More Mathematical Operations
    - On 1-D Arrays
    - On 2-D Arrays
4. Aggregate Functions
    - On 1-D Arrays
    - On 2-D Arrays
5. Comparing NumPy Arrays
    - On 1-D Arrays
    - On 2-D Arrays
6. Bonus: Searching 1-D and 2-D NumPy Arrays using `numpy.where()`

In [1]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install numpy

In [2]:
import numpy as np
np.__version__ , np.__path__

('1.26.4', ['C:\\Users\\attari\\anaconda3\\Lib\\site-packages\\numpy'])

## 1. Scalar Math

### a. Scalar Math on 1-D Arrays

In [3]:
import numpy as np
# Create a 1-D array having 4 random integers from 1 to 9
arr = np.random.randint(1,10, size=4)
print("arr: ", arr)

# After the operation a new `ndarray` is returned
print("np.add(arr,2): ",      arr + 2)            # np.add(arr, 2))
print("np.subtract(arr,2): ", arr - 2)            # np.subtract(arr, 2))
print("np.multiply(arr,2): ", arr * 2)            # np.multiply(arr, 2))
print("np.divide(arr,2): ",   arr / 2)            # np.divide(arr, 2))
print("np.mod(arr,2): ",      arr % 2)            # np.mod(arr, 2))

arr3 = arr + 9
print(id(arr), id(arr3))

arr:  [8 7 8 3]
np.add(arr,2):  [10  9 10  5]
np.subtract(arr,2):  [6 5 6 1]
np.multiply(arr,2):  [16 14 16  6]
np.divide(arr,2):  [4.  3.5 4.  1.5]
np.mod(arr,2):  [0 1 0 1]
2572519739280 2572519739472


### b. Scalar Math on 2-D Arrays

In [4]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("Original matrix:\n", matrix)

# After the operation a new `ndarray` is returned
print("np.add(matrix,2): \n",      matrix + 2)            # np.add(matrix, 2))
print("np.subtract(matrix,2): \n", matrix - 2)            # np.subtract(matrix, 2))
print("np.multiply(matrix,2): \n", matrix * 2)            # np.multiply(matrix, 2))
print("np.divide(matrix,2): \n",   matrix / 2)            # np.divide(matrix, 2))
print("np.mod(matrix,2): \n",      matrix % 2)            # np.mod(matrix, 2))

Original matrix:
 [[9 4]
 [6 4]]
np.add(matrix,2): 
 [[11  6]
 [ 8  6]]
np.subtract(matrix,2): 
 [[7 2]
 [4 2]]
np.multiply(matrix,2): 
 [[18  8]
 [12  8]]
np.divide(matrix,2): 
 [[4.5 2. ]
 [3.  2. ]]
np.mod(matrix,2): 
 [[1 0]
 [0 0]]


## 2. Arithmetic Operations

### a. Arithmetic Operations on 1-D Arrays

In [5]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)

# After the operation a new `ndarray` is returned
print("np.add(arr1, arr2) = ",      arr1 + arr2)     # np.add(arr1, arr2)
print("np.subtract(arr1, arr2) = ", arr1 - arr2)     # np.subtract(arr1, arr2)
print("np.multiply(arr1, arr2) = ", arr1 * arr2)     # np.multiply(arr1, arr2)
print("np.divide(arr1, arr2) = ",   arr1  / arr2)    # np.divide(arr1, arr2)
print("np.mod(arr1, arr2) = ",      arr1  % arr2)    # np.mod(arr1, arr2) # np.remainder(arr1, arr2)

arr1:  [7 1 7 2]
arr2:  [5 7 9 1]
np.add(arr1, arr2) =  [12  8 16  3]
np.subtract(arr1, arr2) =  [ 2 -6 -2  1]
np.multiply(arr1, arr2) =  [35  7 63  2]
np.divide(arr1, arr2) =  [1.4        0.14285714 0.77777778 2.        ]
np.mod(arr1, arr2) =  [2 1 7 0]


### b. Arithmetic Operations on 2-D Arrays

In [6]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)

# After the operation a new `ndarray` is returned
print("np.add(matrix1 , matrix2) = \n",      matrix1 + matrix2) # np.add(matrix1 , matrix2)
print("np.subtract(matrix1 , matrix2) = \n", matrix1 - matrix2) # np.subtract(matrix1 , matrix2)
print("np.multiply(matrix1 , matrix2) = \n", matrix1 * matrix2) # np.multiply(matrix1 , matrix2)
print("np.divide(matrix1 , matrix2) = \n",   matrix1 / matrix2) # np.divide(matrix1 , matrix2)
print("np.mod(matrix1 , matrix2) = \n",      matrix1 % matrix2) # np.remainder(matrix1 , matrix2)

matrix1: 
 [[7 9]
 [3 3]]
matrix2: 
 [[4 9]
 [1 7]]
np.add(matrix1 , matrix2) = 
 [[11 18]
 [ 4 10]]
np.subtract(matrix1 , matrix2) = 
 [[ 3  0]
 [ 2 -4]]
np.multiply(matrix1 , matrix2) = 
 [[28 81]
 [ 3 21]]
np.divide(matrix1 , matrix2) = 
 [[1.75       1.        ]
 [3.         0.42857143]]
np.mod(matrix1 , matrix2) = 
 [[3 0]
 [0 3]]


## 3. More Mathematical Operations

### a. Mathematical Operations on 1-D Array

In [7]:
# Creating 1-D array of 5 elements of random floats between 1 and 10
arr = np.random.rand(5)*10
print("Original ndarray: ", arr)


# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.abs(arr) = ", np.abs(arr))
print("np.square(arr) = ", np.square(arr))
print("np.sqrt(arr) = ", np.sqrt(arr))
print("np.cbrt(arr) = ", np.cbrt(arr))
print("np.log(arr) = ", np.log(arr))
print("np.log2(arr) = ", np.log2(arr))
print("np.log10(arr) = ", np.log10(arr))
print("np.isnan(arr) = ", np.isnan(arr))
print("np.ceil(arr) = ", np.ceil(arr))
print("np.floor(arr) = ", np.floor(arr))
print("np.cumsum(arr) = ", np.cumsum(arr))

Original ndarray:  [6.84591407 6.86774133 3.46915784 3.04380118 1.0144755 ]
np.abs(arr) =  [6.84591407 6.86774133 3.46915784 3.04380118 1.0144755 ]
np.square(arr) =  [46.86653947 47.16587102 12.03505612  9.2647256   1.02916053]
np.sqrt(arr) =  [2.61646977 2.62063758 1.86256754 1.7446493  1.00721174]
np.cbrt(arr) =  [1.89879093 1.9008068  1.51382156 1.44923482 1.00480207]
np.log(arr) =  [1.92365199 1.92683528 1.24391187 1.11310712 0.01437173]
np.log2(arr) =  [2.77524318 2.7798357  1.79458548 1.60587412 0.02073402]
np.log10(arr) =  [0.83543144 0.83681393 0.54022406 0.48341628 0.00624156]
np.isnan(arr) =  [False False False False False]
np.ceil(arr) =  [7. 7. 4. 4. 2.]
np.floor(arr) =  [6. 6. 3. 3. 1.]
np.cumsum(arr) =  [ 6.84591407 13.7136554  17.18281324 20.22661442 21.24108992]


### b. Mathematical Operations on 2-D Array

In [8]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("matrix: \n", matrix)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.square(matrix) = \n", np.square(matrix))
print("np.sqrt(matrix) = \n", np.sqrt(matrix))
print("np.log2(matrix) = \n", np.log2(matrix))
print("np.isnan(matrix) = \n", np.isnan(matrix))
print("np.ceil(matrix) = \n", np.ceil(matrix))
print("np.floor(matrix) = \n", np.floor(matrix))
print("np.cumsum(matrix) = \n", np.cumsum(matrix))

matrix: 
 [[4 7]
 [1 4]]
np.square(matrix) = 
 [[16 49]
 [ 1 16]]
np.sqrt(matrix) = 
 [[2.         2.64575131]
 [1.         2.        ]]
np.log2(matrix) = 
 [[2.         2.80735492]
 [0.         2.        ]]
np.isnan(matrix) = 
 [[False False]
 [False False]]
np.ceil(matrix) = 
 [[4. 7.]
 [1. 4.]]
np.floor(matrix) = 
 [[4. 7.]
 [1. 4.]]
np.cumsum(matrix) = 
 [ 4 11 12 16]


## 4. Aggregate Functions

### a. Aggregate Functions on 1-D Arrays

In [9]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.min(arr) = ",     np.min(arr))
print("np.max(arr) = ",     np.max(arr))
print("np.sum(arr) = ",     np.sum(arr))
print("np.prod(arr) = ", np.prod(arr))

arr:  [7 7 7 3 2]
np.min(arr) =  2
np.max(arr) =  7
np.sum(arr) =  26
np.prod(arr) =  2058


In [10]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

#Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
print("np.mean(arr) = ",    np.mean(arr))

# The np.average() function computes the weighted average, by multiplying of each array element by its weight
# The np.average() is same as np.mean(), when weight is not specified
print("np.average(arr) = ", np.average(arr))

# Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by 
# adding the product of the corresponding elements and dividing the sum by the sum of weights.
#             Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)

arr1 = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print("\narr1: ", arr1)
print("wts:  ", wts)
print("np.average(arr1, weights=wts) = ", np.average(arr1, weights= wts))



arr:  [4 6 8 3 1]
np.mean(arr) =  4.4
np.average(arr) =  4.4

arr1:  [1 2 3 4]
wts:   [4 3 2 1]
np.average(arr1, weights=wts) =  2.0


In [11]:
# Create a 1-D array having 10 random integers from 1 to 99
arr = np.random.randint(1, 100, size=10)
print("arr: ", arr)

# Median is the value separating the higher half of a data sample from the lower half.
print("np.median(arr) = ",  np.median(arr))

# Percentile is the value below which a given percentage of observations in a group of observations fall.
# 50th percentile is the score at or below which 50% of the scores in the distribution may be found.
print("np.percentile(arr,50) = ",     np.percentile(arr,50))
print("np.percentile(arr,0) = ",     np.percentile(arr,0))
print("np.percentile(arr,100) = ",     np.percentile(arr,100))

# The variance measures the average degree to which each point differs from the mean
# Variance is calculated as the average of squared deviations from mean, i.e., mean((x - x.mean())**2).
print("np.var(arr) = ",    np.var(arr))


# Standard deviation checks how spread out a group of numbers is from the mean
# It is the square root of variance: sqrt(mean((x - x.mean())**2))
print("np.std(arr) = ",    np.std(arr))


arr:  [17 97 35 73 67 96 70 24 92 79]
np.median(arr) =  71.5
np.percentile(arr,50) =  71.5
np.percentile(arr,0) =  17.0
np.percentile(arr,100) =  97.0
np.var(arr) =  788.8
np.std(arr) =  28.085583490467133


### b. Aggregate Functions on 2-D Arrays

In [12]:
import numpy as np
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

print("np.sum(matrix, axis=0) = ",     np.sum(matrix, axis=0))
print("np.sum(matrix, axis=1) = ",     np.sum(matrix, axis=1))


matrix: 
 [[1 3 3]
 [2 7 6]
 [2 9 8]]
np.sum(matrix, axis=0) =  [ 5 19 17]
np.sum(matrix, axis=1) =  [ 7 15 19]


In [13]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

print("np.min(matrix, axis=0) = ",     np.min(matrix, axis=0))
print("np.min(matrix, axis=1) = ",     np.min(matrix, axis=1))

matrix: 
 [[4 7 1]
 [2 9 4]
 [8 1 6]]
np.min(matrix, axis=0) =  [2 1 1]
np.min(matrix, axis=1) =  [1 2 1]


In [14]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)


print("np.mean(matrix, axis=0) = ",     np.mean(matrix, axis=0))
print("np.mean(matrix, axis=1) = ",     np.mean(matrix, axis=1))

matrix: 
 [[1 5 2]
 [6 5 9]
 [8 1 3]]
np.mean(matrix, axis=0) =  [5.         3.66666667 4.66666667]
np.mean(matrix, axis=1) =  [2.66666667 6.66666667 4.        ]


In [15]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

# Median is the value separating the higher half of a data sample from the lower half.
print("np.median(matrix, axis=0) = ",     np.median(matrix, axis=0))
print("np.median(matrix, axis=1) = ",     np.median(matrix, axis=1))

matrix: 
 [[5 4 7]
 [4 5 9]
 [4 6 8]]
np.median(matrix, axis=0) =  [4. 5. 8.]
np.median(matrix, axis=1) =  [5. 5. 6.]


Please do practice calculating the percentile, variance and standard deviation along different axis of a 2-D array

## 5. Comparing NumPy Arrays

### a. Comparing NumPy 1-D Arrays
- Returns a Boolean numpy array containing True/False after doing element wise comparison

In [16]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)
print("np.equal(arr1, arr2) = ",      arr1 == arr2)      # np.equal(arr1, arr2)
print("np.not_equal(arr1, arr2) = ",  arr1 != arr2)      # np.not_equal(arr1, arr2)

print("np.greater(arr1, arr2) = ",      arr1 > arr2)     # np.greater(arr1, arr2)
print("np.greater_equal(arr1, arr2) = ",  arr1 >= arr2)  # np.greater_equal(arr1, arr2)

print("np.less(arr1, arr2) = ",      arr1 < arr2)        # np.less(arr1, arr2)
print("np.less_equal(arr1, arr2) = ",  arr1 <= arr2)     # np.less_equal(arr1, arr2)

arr1:  [9 1 6 5]
arr2:  [8 8 6 5]
np.equal(arr1, arr2) =  [False False  True  True]
np.not_equal(arr1, arr2) =  [ True  True False False]
np.greater(arr1, arr2) =  [ True False False False]
np.greater_equal(arr1, arr2) =  [ True False  True  True]
np.less(arr1, arr2) =  [False  True False False]
np.less_equal(arr1, arr2) =  [False  True  True  True]


### b. Comparing NumPy 2-D Arrays

In [17]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)



print("np.equal(matrix1, matrix2) = \n",        matrix1 == matrix2)     
print("np.not_equal(matrix1, matrix2) = \n",    matrix1 != matrix2)     

print("np.greater(matrix1, matrix2) = \n",      matrix1 > matrix2)    
print("np.greater_equal(matrix1, matrix2) = \n",matrix1 >= matrix2) 

print("np.less(matrix1, matrix2) = \n",         matrix1 < matrix2)       
print("np.less_equal(matrix1, matrix2) = \n",   matrix1 <= matrix2)     

matrix1: 
 [[4 4]
 [9 8]]
matrix2: 
 [[5 1]
 [9 6]]
np.equal(matrix1, matrix2) = 
 [[False False]
 [ True False]]
np.not_equal(matrix1, matrix2) = 
 [[ True  True]
 [False  True]]
np.greater(matrix1, matrix2) = 
 [[False  True]
 [False  True]]
np.greater_equal(matrix1, matrix2) = 
 [[False  True]
 [ True  True]]
np.less(matrix1, matrix2) = 
 [[ True False]
 [False False]]
np.less_equal(matrix1, matrix2) = 
 [[ True False]
 [ True False]]


## 6. Searching NumPy Arrays using `numpy.where()`

### a. Searching NumPy 1-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4, 9, 2, 3, 8])
t1 = np.where(arr == 4)
print(t1)

(array([3, 5, 6], dtype=int64),)


Note: The result is a tuple of 1-D arrays having a single tuple containing the index

In [19]:
import numpy as np
arr = np.array([1, 0, 3, 9, 5, 2, 0, 8])
t1 = np.where(arr == 0)
print(t1)

(array([1, 6], dtype=int64),)


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0)
print(t1)

(array([1, 3, 5, 7], dtype=int64),)


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0, True, False)
print(t1)

[False  True False  True False  True False  True]


Note: The result is a simple 1-D array, when you use the x and y arguments to `np.where()`

### b. Searching NumPy 2-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [22]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 4], [4, 9, 2], [3, 8, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 4)
print(t1)

matrix: 
 [[1 2 3]
 [4 5 4]
 [4 9 2]
 [3 8 6]]
(array([1, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices `(1,0)`, `(1,2)` and `(2,0)`

In [23]:
import numpy as np
matrix = np.array([[1, 2, 0], [4, 5, 0], [4, 9, 2], [3, 0, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 0)
print(t1)

matrix: 
 [[1 2 0]
 [4 5 0]
 [4 9 2]
 [3 0 6]]
(array([0, 1, 3], dtype=int64), array([2, 2, 1], dtype=int64))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices:
`(0,2)`, `(1,2)` and `(3,1)`

In [24]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
(array([0, 2], dtype=int64), array([1, 0], dtype=int64))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for two elements at indices:
`(0,2)` and `(1,0)`

In [25]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0, True, False)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
[[False  True False]
 [False False False]
 [ True False False]
 [False False False]]


**Note:** The result is a simple 2-D array, when you use the `x` and `y` arguments to `np.where()`

In [26]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [4, 5, 4, 2], [8, 4, 9, 2], [4, 3, 8, 6]])
t1 = np.where(arr == 4)
print(t1)

(array([0, 1, 1, 2, 3], dtype=int64), array([3, 0, 2, 1, 0], dtype=int64))


# Part -II (Array Indexing, Subsetting and Slicing)

## Learning agenda of this notebook
Indexing and Slicing are two of the most common operations that you need to be familiar with when working with Numpy arrays. You will use them when you would like to work with a subset of the array.
1. Indexing NumPy Arrays
    - Indexing 1-D NumPy Arrays
    - Indexing 2-D NumPy Arrays
    - Indexing 3-D NumPy Arrays
2. Slicing NumPy Arrays
    - Slicing 1-D NumPy Arrays
    - Slicing 2-D NumPy Arrays
3. Boolean Array Indexing
    - Boolean Indexing on 1-D NumPy Arrays
    - Boolean Indexing on 2-D NumPy Arrays

## 1. Indexing Numpy Arrays
- You can access entire dimension or an individual element of NumPy arrays using indexing.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 and so on.
- You can use negative indixes as well, which starts. from the last element.

### a. Indexing 1-D NumPy Arrays
- Along a single axis, integers are used to select single elements, and so-called slices are used to select ranges and sequences of elements. 
- Positive integers are used to index elements from the beginning of the array (index starts at 0), and negative integers are used to index elements from the end of the array, where the last element is indexed with –1, the second to last element with –2, and so on.

In [27]:
import numpy as np
mylist = [4, 5, 6, 7, 0, 2, 3]
arr = np.array(mylist, dtype=np.uint8)


print("Original Array \n", arr, "\nArray Shape: ",arr.shape)

# You can access specific elements using positive as well as negative index
print("\narr[0] = ", arr[0])
print("arr[6] = ", arr[6])
print("arr[-1] = ", arr[-1])       
print("arr[-7] = ", arr[-7])  


print("arr[7] = ", arr[7])       # IndexError
print("arr[-8] = ", arr[-8])      # IndexError

Original Array 
 [4 5 6 7 0 2 3] 
Array Shape:  (7,)

arr[0] =  4
arr[6] =  3
arr[-1] =  3
arr[-7] =  4


IndexError: index 7 is out of bounds for axis 0 with size 7

### b. Indexing 2-D NumPy Arrays

In [28]:
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("Original Array \n", arr, "\nArray Shape: ",arr.shape)
print("Strides: ", arr.strides)

# You can access specific elements
print("arr[3][2] = ", arr[3][2])
print("arr[3,2] = ", arr[3,2])

# You can access entire rows
print("arr[3] = ", arr[3])

# Negative indexing
print("arr[-1][-2] = ", arr[-1][-2])    
print("arr[-1, -2] = ", arr[-1, -2]) 
print("arr[-3][-3] = ", arr[-3][-3])    
print("arr[-3, -3] = ", arr[-3, -3])    
print("arr[-3] = ", arr[-3])       
print("arr[-1] = ", arr[-1])       


Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Shape:  (5, 4)
Strides:  (16, 4)
arr[3][2] =  4
arr[3,2] =  4
arr[3] =  [7 3 4 9]
arr[-1][-2] =  3
arr[-1, -2] =  3
arr[-3][-3] =  2
arr[-3, -3] =  2
arr[-3] =  [3 2 4 1]
arr[-1] =  [4 0 3 1]


### c. Indexing 3-D NumPy Arrays

In [29]:
import numpy as np
mylist = [
          [[1, 2, 3], [5, 6, 7], [9, 0, 5]],
          [[8, 1, 6], [1, 9, 4], [5, 8, 2]],
         ]
arr = np.array(mylist)
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)
print("Strides:", arr.strides)


Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)
Strides: (36, 12, 4)


In [30]:
# You can access 2-D matrix at first level
print("\narr[0]: \n", arr[0])
# You can access 2-D matrix at second level
print("arr[1]: \n", arr[1])


arr[0]: 
 [[1 2 3]
 [5 6 7]
 [9 0 5]]
arr[1]: 
 [[8 1 6]
 [1 9 4]
 [5 8 2]]


In [31]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# You can access a specific row at a specific level
print("\narr[0][1]: ", arr[0][1])
print("\narr[0, 1]: ", arr[0, 1])
print("arr[1][2]: ", arr[1][2])
print("arr[1, 2]: ", arr[1, 2])

Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)

arr[0][1]:  [5 6 7]

arr[0, 1]:  [5 6 7]
arr[1][2]:  [5 8 2]
arr[1, 2]:  [5 8 2]


In [32]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# You can access a specific element
print("\narr[0][1][2]: ", arr[0][1][2])
print("arr[1][2][1]: ", arr[1][2][1])


Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)

arr[0][1][2]:  7
arr[1][2][1]:  8


In [33]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# Negative indexing
print("\narr[-1][-2][-1]: ", arr[-1][-2][-1])    
print("arr[-2][2]: ", arr[-2][2])    

Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)

arr[-1][-2][-1]:  4
arr[-2][2]:  [9 0 5]


## 2. Slicing NumPy Arrays
- You can slice a numpy array in a similar fashion as we have sliced Python Lists, with two differences:
    - The difference is that NumPy arrays can be sliced in more than one dimension.
    - The other difference is that, when we slice a Python list we get a completely new list, while in case of numPy arrays, you get a **view** of the original array, which is just a way of accessing array data. Thus the original array is not copied in memory.
- An array can be sliced using `:` symbol, which returns the range of elements specified by the index numbers.
- There are three arguments for slicing arrays, all are optional:
```
array[[start]:[stop][:step]]
```

    - start: specifies from where the slicing should start, inclusive (default is 0) 
    - stop: specifies where it has to stop, exclusive (default is end of the array) 
    - step:  is by-default 1
    
Note: Subarrays that are extracted from arrays using slice operations are alternative views of the same underlying array data. This means that they are arrays that refer to the same data in memory as the original array, but with a different strides configuration.

a### a. Slicing 1-D Arrays

In [34]:
import numpy as np
mylist = [4, 5, 6, 7, 0, 2, 3]
arr = np.array(mylist, dtype=np.uint8)
print("Original Array \n", arr, "\nArray Shape = ",arr.shape)

Original Array 
 [4 5 6 7 0 2 3] 
Array Shape =  (7,)


In [35]:
print("\narr[:] = ", arr[:])
print("arr[3:] = ", arr[3:])
print("arr[:4] = ", arr[:4])
print("arr[2:5] = ", arr[2:5])

print("arr[:-2] = ", arr[:-2])
print("arr[-1:] = ", arr[-1:])
print("arr[-1:-4] = ", arr[-1:-4])
print("arr[-1:-4:-1] = ", arr[-1:-4:-1])

# reverse the array using step value as -1
print("arr[::-1] = ", arr[::-1])
print("\nAfter all this arr is same: ", arr)


arr[:] =  [4 5 6 7 0 2 3]
arr[3:] =  [7 0 2 3]
arr[:4] =  [4 5 6 7]
arr[2:5] =  [6 7 0]
arr[:-2] =  [4 5 6 7 0]
arr[-1:] =  [3]
arr[-1:-4] =  []
arr[-1:-4:-1] =  [3 2 0]
arr[::-1] =  [3 2 0 7 6 5 4]

After all this arr is same:  [4 5 6 7 0 2 3]


**Proof of Concept:** Slice of a Python List Returns a New List

In [36]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
# A new list object is created after slicing
list2 = list1[2:5]
list2

[3, 4, 5]

In [38]:
#If we make change to this list, it do not effect the original list
list2[0] = 99

In [39]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
list2

[99, 4, 5]

**Proof of Concept:** Slice of a numPy array returns a **view** of original numPy array

In [41]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# A view of the original numPy array is created after slicing
arr2 = arr1[2:5]
arr2

array([3, 4, 5])

In [43]:
# If we make change to this view, it will ofcourse effect the original array
arr2[0] = 99

In [44]:
arr1

array([ 1,  2, 99,  4,  5,  6,  7,  8,  9])

In [45]:
arr2, arr2.strides

(array([99,  4,  5]), (4,))

### b. Slicing 2-D Arrays
- Slicing a two-dimensional array is very similar to slicing a one-dimensional array. You just use a comma to separate the row slice and the column slice.
- Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [46]:
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Note we have two slice objects (row slice and column slice) in case of 2-D slicing separated by a comma
print("\narr[:,:] = \n", arr[:,:])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[:,:] = 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]


In [47]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Get the row at index 2
print("arr[2] = ", arr[2])      # you can ignore the : symbol for the column part
print("arr[2,:]= ", arr[2,:])   # for better readability give comma separated two values

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)
arr[2] =  [3 2 4 1]
arr[2,:]=  [3 2 4 1]


In [48]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Get the column at index 1 (Get all the row values of column at index 1)
print("arr[:, 1] = ", arr[:, 1])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)
arr[:, 1] =  [2 6 2 3 0]


In [49]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)


In [50]:
# From the row at index 1, slice elements from index 1 to index 2
print("\narr[1, 1:3] = ",arr[1, 1:3])


arr[1, 1:3] =  [6 7]


In [51]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reversing elements of all rows is tricky. 
# Read it as "select all the rows, and in each row reverse all the column values
print("\narr[:, ::-1] =\n", arr[:, ::-1])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[:, ::-1] =
 [[4 3 2 1]
 [8 7 6 5]
 [1 4 2 3]
 [9 4 3 7]
 [1 3 0 4]]


In [52]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reverse elements of all columns is also tricky. Actually you want to reverse the elements of all the rows
# Read it as "select all the columns, and in each column reverse all the row values
print("\narr[::-1, :] =\n", arr[::-1, :])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[::-1, :] =
 [[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]


>- **Slicing 3-D arrays can be performed in the same fashion. The only difference is that we have three comma separated slice objects instead of two and it is a bit tricky to visualize :)**

In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [3, 2, 4, 1], [7, 3, 4, 9], [4, 0, 3, 1] ])
print(arr[3,2])
print(arr[3])
print(arr[-1, -2]) 
print(arr[-3][-3])    
print(arr[-3])       
print(arr[2, 1:3])
print(arr[::-1, :])
print(arr[2::2, 0::2])

4
[7 3 4 9]
3
2
[3 2 4 1]
[2 4]
[[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]
[[3 4]
 [4 3]]


## 3. Boolean/Fancy Array Indexing

- NumPy provides another convenient method to index arrays, called fancy indexing. With fancy indexing, an array can be indexed with another NumPy array, a Python list, or a sequence of integers, whose values select elements in the indexed array. Fancy indexing requires that the elements in the array or list used for indexing are integers.

- Boolean indexing is an extremely intuitive and elegant way of selecting contents from a numPy array based on logical conditions.
- In simple words, we can slice NumPy arrays by either:
    - Provide a condition inside the `[]` operator
    - Provide a Boolean mask corresponding to indexes in the array.
- If the value at an index of that list is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

>- **Note:** Unlike normal slicing which creates a view, Boolean/Fancy Indexing creates a copy of numPy array.

>- **Note:** The Python keywords `and` and `or` do not work with boolean arrays. Use `&` and `|` instead

### a. Boolean/Fancy Indexing on 1-D Arrays

In [54]:
# Fancy Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)
print(arr[np.array([0, 2, 4, 9])])
print(arr[[0, 2, 4, 9]])

Original Array:  [29 84 15 79 87 91 83 12 69 94]
[29 15 87 94]
[29 15 87 94]


In [55]:
# Boolean Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)
print(arr > 50)
print(arr[arr>50])

Original Array:  [57 15 70 57 91 49 25  8 54 22]
[ True False  True  True  True False False False  True False]
[57 70 57 91 54]


In [56]:
# Boolean Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)

# Getting even values from array
print("\narr[arr%2 == 0] = ",arr[arr%2==0])
# Getting odd values from array
print("arr[arr%2 == 1] = ",arr[arr%2==1])

# Getting values greater than 50
print("\narr[arr > 50] = ",arr[arr > 50])
# Getting values between 25 and 75 both exclusive
print("arr[arr>30 & arr<60] = ",arr[(arr>30) & (arr<60)])

Original Array:  [79 21 13 57 93 11 11 10 13 59]

arr[arr%2 == 0] =  [10]
arr[arr%2 == 1] =  [79 21 13 57 93 11 11 13 59]

arr[arr > 50] =  [79 57 93 59]
arr[arr>30 & arr<60] =  [57 59]


In [57]:
# We can use a mask instead of mentioning a condition as done above
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("Original Array: ", arr1)

mask=[False, False, False, True, False]
arr2 = arr1[mask]

print("Filtered Array: ", arr2)  

Original Array:  [1 2 3 4 5]
Filtered Array:  [4]


### b. Boolean/Fancy Indexing on 2-D Arrays

**Example 1:**

In [58]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[5 9 3 6 2]
 [6 9 3 4 9]
 [7 9 2 8 8]
 [4 5 3 6 9]
 [8 5 3 2 4]] 
Matrix Shape =  (5, 5)


>Suppose we want a new matrix from above matrix, that only contains rows at index 0, 2, and 3

In [59]:
# Create a corresponding boolean mask
rows_wanted = np.array( [True, False, True, True, False] )

matrix2 = matrix1[rows_wanted, :]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[5 9 3 6 2]
 [7 9 2 8 8]
 [4 5 3 6 9]] 
Matrix Shape =  (3, 5)


**Example 2:**

In [60]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[2 5 8 2 8]
 [4 3 7 6 3]
 [7 6 9 9 3]
 [8 1 2 1 8]
 [1 6 1 2 4]] 
Matrix Shape =  (5, 5)


>Suppose we want a new matrix from above matrix, that only contains columns at index 1 and 3 only

In [61]:
# Create a corresponding boolean mask
cols_wanted = np.array( [False, True, False, True, False] )

matrix2 = matrix1[ : , cols_wanted]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[5 2]
 [3 6]
 [6 9]
 [1 1]
 [6 2]] 
Matrix Shape =  (5, 2)


**Example 3:**

In [62]:
import numpy as np
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[8 4 6 3 3]
 [5 1 3 9 1]
 [5 5 7 5 4]
 [2 1 8 3 3]
 [8 2 8 2 8]] 
Matrix Shape =  (5, 5)


In [63]:
rows_wanted = np.array( [False, True, True, True, False] )

matrix2 = matrix1[ rows_wanted , :]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[5 1 3 9 1]
 [5 5 7 5 4]
 [2 1 8 3 3]] 
Matrix Shape =  (3, 5)


In [64]:
cols_wanted = np.array( [False, True, True, True, False] )

matrix3 = matrix2[ :, cols_wanted]
print("\nFiltered matrix \n", matrix3, "\nMatrix Shape = ",matrix3.shape)


Filtered matrix 
 [[1 3 9]
 [5 7 5]
 [1 8 3]] 
Matrix Shape =  (3, 3)


**Can you think of doing this in one step or in a more elegant fashion?**

In [65]:
matrix3 = matrix1[1:4, 1:4]
print("\nFiltered matrix \n", matrix3, "\nMatrix Shape = ",matrix3.shape)


Filtered matrix 
 [[1 3 9]
 [5 7 5]
 [1 8 3]] 
Matrix Shape =  (3, 3)


In [66]:
matrix2 = matrix1[ 1 : -1,  1 : -1 ]
matrix2

array([[1, 3, 9],
       [5, 7, 5],
       [1, 8, 3]])

# Four Slicing Problems with Solutions

In [67]:
m1 = np.array([
            [0,1,2,3,4,5],
            [6,7,8,9,10,11],
            [12,13,14,15,16,17],
            [18,19,20,21,22,23],
            [24,25,26,27,28,29],
            [30,31,32,33,34,35]
])

In [68]:
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
m1[0,3:5]

array([3, 4])

In [70]:
m1[4:, 4:]

array([[28, 29],
       [34, 35]])

In [71]:
m2 = m1[:,2]

In [72]:
m2.strides

(24,)

In [73]:
m1[2::2, 0::2]

array([[12, 14, 16],
       [24, 26, 28]])